language: node_js
node_js:
 - "stable"
cache:
 directories:
 - node_modules
script:
 - npm run build
 - npm install surge
deploy:
  provider: surge
  project: ./build/
  domain: hnryjmes-maps-app.surge.sh
  skip_cleanup: true
